# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MeshCodeViewer
                                 A QGIS plugin
 このプラグインは、Grid square statistics（ISO 24108）及び地域メッシュ統計(JIS X 0410)に基づくメッシュを背景地図に表示します。
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-08-22
        copyright            : (C) 2026 by S. Takahashi / 一般社団法人世界メッシュ研究所
        email                : kametarou3000@outlook.jp
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MeshCodeViewer class from file MeshCodeViewer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .mesh_code_viewer import MeshCodeViewer
    return MeshCodeViewer(iface)
