# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MeshCodeViewerDialog
                                 A QGIS plugin
 このプラグインは、Grid square statistics（ISO 24108）及び地域メッシュ統計(JIS X 0410)に基づくメッシュを背景地図に表示します。
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-08-22
        git sha              : $Format:%H$
        copyright            : (C) 2026 by S. Takahashi / 一般社団法人世界メッシュ研究所
        email                : kametarou3000@outlook.jp
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(
    os.path.join(
        os.path.dirname(__file__),
        'mesh_code_viewer_dialog_base.ui'),
    from_imports=True,
    import_from='mesh_code_viewer')


class MeshCodeViewerDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(MeshCodeViewerDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        # 初期選択
        self.radioButton.setChecked(True)

        # # default設定
        self.comboBox.addItems(
            ['1次メッシュ（約80km）', '2次メッシュ（約10km）', '5倍メッシュ（約5km）', '2倍メッシュ（約2km）',
             '3次メッシュ（約1km）', '4次メッシュ（約500m）', '5次メッシュ（約250m）',
             '拡張200mメッシュ（約200m）', '6次メッシュ（約125m）', '拡張100mメッシュ（約100m）',
             '拡張50mメッシュ（約50m）', '拡張20mメッシュ（約20m）', '拡張10mメッシュ（約10m）',
             '拡張5mメッシュ（約5m）', '拡張2mメッシュ（約2m）', '拡張1mメッシュ（約1m）'])

        self.radioButton.toggled.connect(self.update_list)
        # self.radioButton_2.toggled.connect(self.update_list)




    def accept(self):
        pass

    def update_list(self, checked):
        self.comboBox.clear()
        if self.radioButton.isChecked():
            self.comboBox.addItems(['1次メッシュ（約80km）', '2次メッシュ（約10km）', '5倍メッシュ（約5km）', '2倍メッシュ（約2km）',
                                '3次メッシュ（約1km）', '4次メッシュ（約500m）',  '5次メッシュ（約250m）',
                                '拡張200mメッシュ（約200m）', '6次メッシュ（約125m）', '拡張100mメッシュ（約100m）',
                                '拡張50mメッシュ（約50m）', '拡張20mメッシュ（約20m）', '拡張10mメッシュ（約10m）',
                                '拡張5mメッシュ（約5m）', '拡張2mメッシュ（約2m）', '拡張1mメッシュ（約1m）'])
        else:
            self.comboBox.addItems(['1次地域メッシュ（約80km）', '2次地域メッシュ（約10km）', '5倍地域メッシュ（約5km）',
                                    '2倍地域メッシュ（約2km）', '3次（基準）地域メッシュ（約1km）', '２分の１地域メッシュ（約500m）',
                                    '４分の１地域メッシュ（約250m）', '８分の１地域次メッシュ（約125m）'])

