# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MeshCodeViewer
                                 A QGIS plugin
 このプラグインは、Grid square statistics（ISO 24108）及び地域メッシュ統計(JIS X 0410)に基づくメッシュを背景地図に表示します。
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-08-22
        git sha              : $Format:%H$
        copyright            : (C) 2026 by S. Takahashi / 一般社団法人世界メッシュ研究所
        email                : kametarou3000@outlook.jp
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QLocale, QTranslator, QCoreApplication
from qgis.core import QgsSettings
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Import the code for the dialog
from .mesh_code_viewer_dialog import MeshCodeViewerDialog
import os.path
import math

# 追加のライブラリ
from qgis.core import (
    QgsCoordinateReferenceSystem,
    QgsCoordinateTransform,
    QgsProject,
    QgsPointXY,
    QgsApplication,
    QgsVectorLayer,
    QgsFeature,
    QgsGeometry,
    QgsFields,
    QgsField,
    QgsFillSymbol,
    QgsPalLayerSettings,
    QgsVectorLayerSimpleLabeling,
    QgsTextFormat,
    QgsUnitTypes,
    Qgis
)
from qgis.PyQt.QtGui import QColor, QFont
from PyQt5.QtGui import QColor
from PyQt5.QtCore import QVariant
from .lib.latitude_and_longitude import LatitudeAndLongitude
from .lib.coordinate import Coordinate
from qgis.PyQt.QtWidgets import QMessageBox


class MeshCodeViewer:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QgsSettings().value('locale/userLocale', QLocale().name())[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            '{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Mesh Code Viewer')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None
        
    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('MeshCodeViewer', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = os.path.join(os.path.dirname(__file__), 'icon.png')
        self.add_action(
            icon_path,
            text=self.tr(u''),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Mesh Code Viewer'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = MeshCodeViewerDialog()

            # 追加行①
            # メッシュの表示（OKボタン）
            try:
                self.dlg.button_box.accepted.disconnect()
            except TypeError:
                pass
            self.dlg.button_box.accepted.connect(self.draw_meshes)

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass

    # 追加行②
    def draw_meshes(self):
        self.type_of_code = self.dlg.radioButton.isChecked()
        self.wgs = WGS(self.iface)
        self.mesh_size_no = self.dlg.comboBox.currentIndex()
        # self.mesh_size_coefficient = int(self.dict_meshsize_no[mesh_size_no])
        self.state = self.dlg.checkBox.isChecked()
        self.mesh_size_text = self.dlg.comboBox.currentText()
        number_of_meshes = self.wgs.draw_meshes(self.mesh_size_no, self.state, self.mesh_size_text, self.type_of_code)
        self.dlg.textBrowser.setText(number_of_meshes)

class WGS:
    def __init__(self, iface):
        self.iface = iface
        self.meshcodeviewer = MeshCodeViewer(self.iface)
        self.dlg = MeshCodeViewerDialog()

        self.limit_number = 100

    def get_extent(self):
        # 現在のキャンバスの表示範囲（地図座標系）
        extent = self.iface.mapCanvas().extent()

        # 現在のプロジェクトの CRS（例: EPSG:qgis ラスタレイヤ 画面表示されている四隅の緯度経度をpythonで求める方法3857 など）
        src_crs = self.iface.mapCanvas().mapSettings().destinationCrs()

        # 緯度経度（EPSG:4326）に変換するための CRS
        dest_crs = QgsCoordinateReferenceSystem("EPSG:4326")
        # dest_crs = QgsCoordinateReferenceSystem("EPSG:3857")

        # 座標変換オブジェクトを作成
        transform = QgsCoordinateTransform(src_crs, dest_crs, QgsProject.instance())

        # 四隅の座標を変換
        top_left = transform.transform(extent.xMinimum(), extent.yMaximum())
        top_right = transform.transform(extent.xMaximum(), extent.yMaximum())
        bottom_left = transform.transform(extent.xMinimum(), extent.yMinimum())
        bottom_right = transform.transform(extent.xMaximum(), extent.yMinimum())

        return {"top_left": {"latitude": top_left.y(), "longitude": top_left.x()},
                "top_right": {"latitude": top_right.y(), "longitude": top_right.x()},
                "bottom_left": {"latitude": bottom_left.y(), "longitude": bottom_left.x()},
                "bottom_right": {"latitude": bottom_right.y(), "longitude": bottom_right.x()}}


    def draw_meshes(self, mesh_size_no, checkbox_state, selected_item, type_of_code):
        self.prefix = "20"
        if type_of_code:
            self.dict_meshsize_no = {0: 80000, 1: 10000, 2: 5000, 3: 2000, 4: 1000, 5: 500, 6: 250, 7: 200, 8: 125, 9: 100,
                                    10: 50, 11: 20, 12: 10, 13: 5, 14: 2, 15: 1}
        else:
            self.dict_meshsize_no = {0: 80000, 1: 10000, 2: 5000, 3: 2000, 4: 1000, 5: 500, 6: 250, 7:125}
            self.prefix = ""

        mesh_size_coefficient = self.dict_meshsize_no[mesh_size_no]
        # 東西南北の座標
        self.extent = self.get_extent()

        # 東西南北のxy座標
        self.coordinate_bottom_left = LatitudeAndLongitude(latitude = self.extent["bottom_left"]["latitude"],
                                   longitude=self.extent["bottom_left"]["longitude"]).get_coordinate(mesh_size_coefficient)
        self.coordinate_top_right = LatitudeAndLongitude(latitude = self.extent["top_right"]["latitude"],
                                   longitude=self.extent["top_right"]["longitude"]).get_coordinate(mesh_size_coefficient)

        mesh_number = (self.coordinate_top_right["x"] - self.coordinate_bottom_left["x"] + 1) \
                    * (self.coordinate_top_right["y"] - self.coordinate_bottom_left["y"] + 1)

        # メッシュ数がlimit_numberを超えない設定
        if mesh_number > self.limit_number:
            QMessageBox.information(None, "警告", f"メッシュが{self.limit_number}を超えています。\n再設定してください。", QMessageBox.Yes)
        else:
            # 範囲内の全座標
            self.coordinates = [{"x": x, "y": y} for x in
                                range(self.coordinate_bottom_left["x"], self.coordinate_top_right["x"] + 1)
                                for y in range(self.coordinate_bottom_left["y"], self.coordinate_top_right["y"] + 1)]

            # coordinateからwktを作成
            self.data = []

            for coordinate in self.coordinates:
                latitude_North = (coordinate["y"] + 1) * 2 / 3 / (80000 / mesh_size_coefficient)
                latitude_South = coordinate["y"] * 2 / 3 / (80000 / mesh_size_coefficient)
                longitude_East = (coordinate["x"] + 1) / (80000 / mesh_size_coefficient) + 100
                longitude_West = coordinate["x"] / (80000 / mesh_size_coefficient) + 100
                data = {"coordinate": str(coordinate["x"])+","+str(coordinate["y"]),
                        "WKT": LatitudeAndLongitude.dict2wkt(North=latitude_North,
                                                             South=latitude_South,
                                                             East=longitude_East,
                                                             West=longitude_West),
                        "meshcode":self.prefix + str(Coordinate(x=coordinate["x"], y=coordinate["y"]).get_mesh_code(mesh_size_coefficient)),

                        "latitude_North": latitude_North,
                        "latutude_South": latitude_South,
                        "longitude_East": longitude_East,
                        "longitude_West": longitude_West,
                        "distance_vertical": LatitudeAndLongitude.distance(latitude_a=latitude_South,
                                                                             longitude_a=longitude_West,
                                                                             latitude_b=latitude_North,
                                                                             longitude_b=longitude_West),
                        "distance_horizontal(North)": LatitudeAndLongitude.distance(latitude_a=latitude_North,
                                                                                      longitude_a=longitude_West,
                                                                                      latitude_b=latitude_North,
                                                                                      longitude_b=longitude_East),
                        "distance_horizontal(South)": LatitudeAndLongitude.distance(latitude_a=latitude_South,
                                                                                      longitude_a=longitude_West,
                                                                                      latitude_b=latitude_South,
                                                                                      longitude_b=longitude_East),
                        "rectangle_area": round(LatitudeAndLongitude.rectangle_area(latitude_a=latitude_South,
                                                                                longitude_a=longitude_West,
                                                                                latitude_b=latitude_South,
                                                                                longitude_b=longitude_East,
                                                                                latitude_c=latitude_North,
                                                                                longitude_c=longitude_East,
                                                                                latitude_d=latitude_North,
                                                                                longitude_d=longitude_West), 3)
                }
                self.data.append(data)

            layer = QgsVectorLayer('Polygon', selected_item, 'memory')
            pr = layer.dataProvider()

            # new fieldの追加
            new_fields = [QgsField("メッシュコード", QVariant.String),
                          QgsField("緯度（北）", QVariant.String),
                          QgsField("緯度（南）", QVariant.String),
                          QgsField("経度（東）", QVariant.String),
                          QgsField("経度（西）", QVariant.String),
                          QgsField("長さ（縦）(km)", QVariant.String),
                          QgsField("長さ（横（北））(km)", QVariant.String),
                          QgsField("長さ（横（南））(km)", QVariant.String),
                          QgsField("面積(km2)", QVariant.String),
                          ]
            pr.addAttributes(new_fields)
            layer.updateFields()

            for row in self.data:
                # polygon追加
                poly = QgsFeature()
                geom = QgsGeometry.fromWkt(row["WKT"])
                poly.setGeometry(geom)

                # new fieldに
                poly.setAttributes([row["meshcode"],
                                    row["latitude_North"],
                                    row["latutude_South"],
                                    row["longitude_East"],
                                    row["longitude_West"],
                                    row["distance_vertical"],
                                    row["distance_horizontal(North)"],
                                    row["distance_horizontal(South)"],
                                    row["rectangle_area"],
                                    ])

                # new featureを追加
                pr.addFeatures([poly])

                #     ラベル表示
                #     ラベル設定
                if checkbox_state == True:
                #     ラベル設定
                    label_settings = QgsPalLayerSettings()
                    label_settings.fieldName = "メッシュコード"  # 属性テーブルの地物名カラム名
                    label_settings.placement = Qgis.LabelPlacement.OverPoint

                # ラベルのスタイル設定
                text_format = label_settings.format()
                text_format.setFont(QFont("MS Gothic"))
                text_format.setColor(QColor(0, 0, 128))

                # 画面スケール
                scale = self.iface.mapCanvas().scale()
                text_format.setSize(10)
                # text_format.setSize(scale / 20000)
                text_format.setSizeUnit(QgsUnitTypes.RenderPoints)
                label_settings.setFormat(text_format)

                # ラベル有効化
                layer.setLabelsEnabled(True)
                layer.setLabeling(QgsVectorLayerSimpleLabeling(label_settings))
                layer.triggerRepaint()

            layer.updateExtents()

            # 現在のシンボルを取得
            symbol = layer.renderer().symbol()

            # 塗りつぶし色を取得
            current_color = symbol.color()

            # 新しい色（透明度を下げる）
            # QColor(R, G, B, Alpha)  Alpha=0〜255
            new_color = QColor(current_color.red(),
                               current_color.green(),
                               current_color.blue(),
                               100)  # 100 は半透明

            # 色を設定
            symbol.setColor(new_color)

            # レイヤーを再描画
            layer.triggerRepaint()

            QgsProject.instance().addMapLayers([layer])

            return str(len(self.data))

            pass